steps:
  # Cancel any previous builds for this service to prioritize the latest
  # BUT keep builds with the same commit SHA (they're part of the same deployment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Cancelling outdated builds for ${_SERVICE_NAME}..."
        # Get current build ID and commit SHA from environment
        current_build_id=$BUILD_ID
        current_commit_sha=${SHORT_SHA}
        echo "Current build ID: $current_build_id"
        echo "Current commit SHA: $current_commit_sha"
        
        # Get all ongoing builds for this service as JSON to check commit SHA
        ongoing_builds_json=$(gcloud builds list \
          --region=${_REGION} \
          --filter="status=QUEUED OR status=WORKING OR status=PENDING" \
          --filter="substitutions._SERVICE_NAME=${_SERVICE_NAME}" \
          --filter="id!=$current_build_id" \
          --format="json" \
          --sort-by=~createTime \
          --project=${PROJECT_ID} 2>/dev/null || echo "[]")
        
        if [ "$ongoing_builds_json" != "[]" ] && [ -n "$ongoing_builds_json" ]; then
          cancelled=0
          kept=0
          
          # Use jq to parse JSON and filter by commit SHA
          # Only cancel builds with different commit SHA
          echo "$ongoing_builds_json" | jq -r ".[] | select(.substitutions.SHORT_SHA != \"$current_commit_sha\") | .id" | while read build_id; do
            if [ -n "$build_id" ] && [ "$build_id" != "$current_build_id" ]; then
              echo "Cancelling outdated build (different commit): $build_id"
              gcloud builds cancel "$build_id" --region=${_REGION} --project=${PROJECT_ID} --quiet 2>/dev/null || true
              cancelled=$((cancelled + 1))
            fi
          done
          
          # Count builds kept (same commit)
          kept=$(echo "$ongoing_builds_json" | jq -r "[.[] | select(.substitutions.SHORT_SHA == \"$current_commit_sha\")] | length" 2>/dev/null || echo "0")
          
          if [ "$cancelled" -gt 0 ]; then
            echo "Cancelled $cancelled outdated build(s) (different commits)"
          fi
          if [ "$kept" -gt 0 ]; then
            echo "Kept $kept build(s) with same commit SHA (part of same deployment)"
          fi
        else
          echo "No outdated builds to cancel"
        fi
    id: 'cancel-outdated-builds'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'services/${_SERVICE_NAME}/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--project'
      - '${PROJECT_ID}'

substitutions:
  _REGION: 'europe-west1'
  _ARTIFACT_REGISTRY: 'credovo-services'
  _SERVICE_NAME: 'orchestration-service'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

